Rewrite without dolittle
RaaLabs/Modbus pull request #22
Opened 2021-04-14 15:34 UTC by thotokraa

2021-04-14 21:26 UTC, srudaa requested changes
Great work! 

You can find my comments in each file. 

Summary and other questions: 
1) Please check code smells for Master.cs in sonar cloud. 
2) Add *.feature.cs in gitignore
3) Should it be Specs or Specifications? Other modules like IdentityMapper has Specifications.
4) Code coverage is not reported to sonar cloud.

2021-04-14 21:26 UTC, srudaa commented on Source/ByteExtensions.cs
> +        /// <param name="source"></param>
What is source?

2021-04-14 21:26 UTC, srudaa commented on Source/Dockerfile-old
> +ENTRYPOINT ["dotnet", "RaaLabs.Edge.Connectors.Modbus.dll"]
Delete this file?

2021-04-14 21:26 UTC, srudaa commented on Source/EndiannessExtensions.cs
> +        /// <param name="shorts"></param>
what is shorts?

2021-04-14 21:26 UTC, srudaa commented on Source/Events/ModbusDatapointOutput.cs
> +    [ExcludeFromCodeCoverage]
Can remove ExcludeFromCodeCoverage. Tested using HandlerSteps

2021-04-14 21:26 UTC, srudaa commented on Source/Events/ModbusRegisterReceived.cs
> +    [ExcludeFromCodeCoverage]
Can remove ExcludeFromCodeCoverage. Tested using HandlerSteps

2021-04-14 21:26 UTC, srudaa commented on Source/Modbus.csproj
>          <PackageReference Include="nmodbus" Version="3.0.58" />
Bump to 3.0.62?

2021-04-14 21:26 UTC, srudaa commented on Source/ModbusRegisterReceivedHandler.cs
> +            var timestamp = (long)(DateTime.UtcNow - new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)).TotalMilliseconds;
How about this?  DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()

2021-04-14 21:26 UTC, srudaa commented on Source/ModbusRegisterReceivedHandler.cs
> +                    _logger.Information($"Tag: {tagWithData.Tag}, Value : {tagWithData.Data}");
Remove logger. Framework will generate similar log when SendEvent is called.

2021-04-14 21:26 UTC, srudaa commented on Source/ModbusRegisterReceivedHandler.cs
> +    ///
Add doc

2021-04-14 21:26 UTC, srudaa commented on Source/Model/TagWithData.cs
> +namespace RaaLabs.Edge.Connectors.Modbus.Model
Add doc

2021-04-14 21:26 UTC, srudaa commented on Source/Program.cs
>      class Program
static class Program

2021-04-14 21:26 UTC, srudaa commented on Source/data/_streamingConnectors.json
> +{
Delete?

2021-04-14 21:26 UTC, srudaa commented on Specs/Features/EndiannessExtensions.feature.cs
> +﻿// ------------------------------------------------------------------------------
Delete file and add *.feature.cs in gitignore

2021-04-14 21:26 UTC, srudaa commented on Specs/Features/ModbusBridge.feature.cs
> +#region Designer generated code
Delete file and add *.feature.cs in gitignore

2021-04-14 21:26 UTC, srudaa commented on Specs/Features/ModbusRegisterReceivedHandler.feature.cs
> +﻿// ------------------------------------------------------------------------------
Delete file and add *.feature.cs in gitignore

2021-04-14 21:26 UTC, srudaa commented on Specs/Specs.csproj
> +
Format doc

2021-04-15 17:20 UTC, thotokraa commented on Source/Bridge/Master.cs
>      public class Master : IMaster, IDisposable
I realized that there's no point in making this class implement `IDisposable` anymore, so I removed it.

2021-04-15 17:20 UTC, thotokraa commented on Source/Dockerfile-old
> +ENTRYPOINT ["dotnet", "RaaLabs.Edge.Connectors.Modbus.dll"]
Done.

2021-04-15 17:20 UTC, thotokraa commented on Source/EndiannessExtensions.cs
> +        /// <param name="shorts"></param>
Added comment about this.

2021-04-15 17:20 UTC, thotokraa commented on Source/Events/ModbusDatapointOutput.cs
> +    [ExcludeFromCodeCoverage]
Done.

2021-04-15 17:20 UTC, thotokraa commented on Source/Events/ModbusRegisterReceived.cs
> +    [ExcludeFromCodeCoverage]
Done.

2021-04-15 17:20 UTC, thotokraa commented on Source/Modbus.csproj
>          <PackageReference Include="nmodbus" Version="3.0.58" />
Done.

2021-04-15 17:20 UTC, thotokraa commented on Source/ModbusRegisterReceivedHandler.cs
> +    ///
Done.

2021-04-15 17:20 UTC, thotokraa commented on Source/Model/TagWithData.cs
> +namespace RaaLabs.Edge.Connectors.Modbus.Model
Removed the class instead, as it was not necessary.

2021-04-15 17:20 UTC, thotokraa commented on Source/Program.cs
>      class Program
Done.

2021-04-15 17:28 UTC, thotokraa commented on Source/data/_streamingConnectors.json
> +{
Done.

2021-04-22 13:03 UTC, srudaa approved these changes

2021-04-22 13:03 UTC, merged